version: "3.9"

services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/backend
    ports:
      - 8888:8000
    environment:
      - DB_HOST=db
      - DB_NAME=ambassador_db
      - DB_USER=ambassador_user
      - DB_PASS=ambassador_pass
    depends_on:
      - db
      - redis

  db:
    container_name: pgdb
    image: postgres:13-alpine
    volumes:
    - .db:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=ambassador_db
      - POSTGRES_USER=ambassador_user
      - POSTGRES_PASSWORD=ambassador_pass

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 63799:6379
